import LiteracyCoach from './LiteracyCoach.jsx';
const RBI='https://www.rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=53185';
const MHA='https://www.pib.gov.in/PressReleasePage.aspx?PRID=1814120&lang=2&reg=3';
const SEBI='https://investor.sebi.gov.in/spot-any-scam.html';
const practice={risk_score:60,flags:[{id:'amount_payout',phrase:'Invest 499 and I will give you 1500.',en:'A promise to repay much more than the deposit is a reason to check independently, not proof of fraud.',hi:'बहुत ज्यादा रकम लौटाने का वादा अलग से जांच करने का कारण है, धोखाधड़ी का प्रमाण नहीं।',source:SEBI}],links:[],label:'promotion'};
export function LearnPage({lang,t}) {
 const hi=lang==='hi';return <section className="info-page"><p>{hi?'यह काल्पनिक अभ्यास है, आपके निजी संदेश या भुगतान का परिणाम नहीं। किसी वास्तविक भुगतान को सुरक्षित नहीं घोषित करता।':'This is fictional practice, not analysis of your private message or payment. It does not declare a real payment safe.'}</p><blockquote className="fictional-example">Invest 499 and I will give you 1500.</blockquote><LiteracyCoach data={practice} lang={lang} t={t}/><a className="note-button" href="#/check/message">{hi?'अपना संदेश जांचें':'Check your own message'}</a><p className="disclaimer-box">{hi?'पैसे भेज दिए हैं? पहले मदद लें।':'Already sent money? Get help first.'} <a href="#/help">{hi?'तुरंत मदद':'Urgent help'}</a></p></section>;
}
export function HelpPage({lang}) {
 const hi=lang==='hi';return <section className="info-page">
 <p className="error-note">{hi?'पैसे चले गए या बैंक जानकारी साझा की? तुरंत कार्रवाई करें। इस ऐप की जांच या टाइमर खत्म होने का इंतजार न करें।':'Money lost or banking details shared? Act immediately. Do not wait for this app to analyse or for a timer to finish.'}</p>
 <ol className="help-steps"><li><h2>{hi?'अपने बैंक से तुरंत संपर्क करें':'Contact your bank immediately'}</h2><p>{hi?'अपने बैंक का आधिकारिक ऐप, वेबसाइट या कार्ड पर दिए नंबर का उपयोग करें। संदिग्ध संदेश में दिए नंबर पर भरोसा न करें। संदिग्ध या अनधिकृत भुगतान बताएं और खाते की सुरक्षा के कदम पूछें।':'Use your bank’s official app, website or number on your card, not a number from the suspicious message. Report suspected fraud or unauthorised activity and ask how to secure the account.'}</p><a href={RBI} target="_blank" rel="noreferrer">{hi?'RBI सुरक्षा सलाह':'RBI safety guidance'}</a></li>
 <li><h2>{hi?'वित्तीय साइबर धोखाधड़ी: 1930':'Financial cyber fraud: 1930'}</h2><p>{hi?'भारत में वित्तीय साइबर धोखाधड़ी तुरंत बताने के लिए आधिकारिक हेल्पलाइन पर संपर्क करें।':'In India, contact the official helpline for immediate reporting of financial cyber fraud.'}</p><a className="note-button" href="tel:1930">{hi?'1930 पर कॉल करें':'Call 1930'}</a><a href={MHA} target="_blank" rel="noreferrer">{hi?'आधिकारिक स्रोत':'Official source'}</a></li>
 <li><h2>{hi?'आधिकारिक पोर्टल पर रिपोर्ट करें':'Report through the official portal'}</h2><p>{hi?'संदेश, भुगतान रसीद और उपलब्ध विवरण सुरक्षित रखें। TipCheck शिकायत जमा नहीं करता और पैसे वापसी की गारंटी नहीं देता।':'Keep the message, payment receipt and available evidence. TipCheck does not file a complaint or guarantee recovery.'}</p><a className="note-button" href="https://cybercrime.gov.in/" target="_blank" rel="noreferrer">{hi?'राष्ट्रीय साइबर अपराध रिपोर्टिंग पोर्टल':'National Cyber Crime Reporting Portal'}</a></li></ol>
 <p className="disclaimer-box">{hi?'स्क्रीन साझा करना बंद करें, OTP/PIN न दें और संदिग्ध व्यक्ति से आगे भुगतान के लिए सहमत न हों। मदद लेने के लिए यहां निजी विवरण न डालें।':'Stop screen sharing, do not share OTPs/PINs and do not agree to further payments to the suspicious party. Do not enter private complaint details here.'}</p>
 </section>;
}
export function AboutPage({lang}) {
 const hi=lang==='hi';return <section className="info-page">
 <h2>{hi?'क्या जांचा जाता है':'What is checked'}</h2><p>{hi?'संदेश में नियमों के संकेत, आपके बताए छह उत्तर और लिंक की स्थानीय बनावट। नियम पहचान और संदर्भ में गलती कर सकते हैं। उत्पादन सर्वर में उपलब्ध हो तो मॉडल केवल संदेश के प्रकार में मदद करता है; जोखिम स्कोर नियमों से आता है।':'Rule-matched message cues, six self-reported answers and local link structure. Rules can miss context or unfamiliar wording. When available on the server, a model helps label the message type; the risk score comes from rules.'}</p>
 <h2>{hi?'स्कोर का मतलब':'What the score means'}</h2><p>{hi?'अनुमानित वजन का योग, अधिकतम 100। संदर्भ अधिकतम 60 और लिंक की बनावट अधिकतम 10 जोड़ती है। कुछ दोहराए संकेत दोबारा नहीं गिने जाते। यह मापी हुई सटीकता या धोखाधड़ी की संभावना नहीं है। शून्य सुरक्षा का प्रमाण नहीं।':'A sum of heuristic weights, capped at 100. Context adds at most 60 and link structure at most 10. Some repeated cues are not counted twice. This is not measured accuracy or scam probability. Zero does not prove safety.'}</p>
 <h2>{hi?'क्या नहीं किया जाता':'What is not done'}</h2><p>{hi?'लिंक खोलना, बैंक/UPI डेटा लेना, व्यक्ति की प्रतिष्ठा या पंजीकरण सत्यापित करना, WhatsApp पढ़ना, भुगतान रोकना या किसी को संदेश भेजना। 30 सेकंड का टाइमर केवल स्वैच्छिक याद दिलाता है।':'No link opening, bank/UPI data access, payee reputation or registration verification, WhatsApp reading, payment blocking or contact alerts. The 30-second timer is only a voluntary reminder.'}</p>
 <h2>{hi?'आपके विवरण और गोपनीयता':'Your details and privacy'}</h2><p>{hi?'लिखते समय विवरण इसी टैब की मेमोरी में रहते हैं। रीफ्रेश से मिट जाते हैं। समीक्षा में जांच बटन दबाने पर संदेश और दिखाए उत्तर निर्धारित विश्लेषण सर्वर पर जाते हैं। यह ऐप अनुरोध के शब्द जानबूझकर लॉग या उत्तर सहेजता नहीं, न खाता, निजी इतिहास या विश्लेषिकी जोड़ता है। होस्टिंग सेवा की नीति अलग हो सकती है; यह शून्य डेटा रखे जाने की गारंटी नहीं।':'While you fill the flow, details stay in this tab’s memory and are cleared by refresh. Pressing analysis on Review sends the message and displayed answers to the configured analysis server. This app does not intentionally log request text, save answers, add accounts, private history or analytics. Hosting providers may have separate policies; this is not a guarantee of zero infrastructure retention.'}</p>
 <p className="disclaimer-box">{hi?'PIN, OTP, बैंक खाते, पहचान दस्तावेज या व्यक्ति के नाम न डालें। भेजने से पहले संदेश से निजी जानकारी हटा दें।':'Do not enter PINs, OTPs, account details, identity documents or recipient names. Remove private details from messages before sending.'}</p>
 <h2>{hi?'स्रोत और सीमाएं':'Sources and limits'}</h2><ul className="source-list"><li><a href={RBI} target="_blank" rel="noreferrer">RBI: {hi?'साइबर धोखाधड़ी और सुरक्षित बैंकिंग':'cyber fraud and safe banking'}</a></li><li><a href={SEBI} target="_blank" rel="noreferrer">SEBI: {hi?'धोखाधड़ी के संकेत':'spotting scam signals'}</a></li><li><a href="https://www.npci.org.in/uploads/UPI_OC_No_101_A_FY_2025_26_Strengthening_beneficiary_name_verification_and_display_during_UPI_transactions_eb7bd7ed72.pdf" target="_blank" rel="noreferrer">NPCI: {hi?'बैंक में दिखने वाला लाभार्थी नाम':'bank-displayed beneficiary name'}</a></li></ul><p>{hi?'यह अभी विकासाधीन निर्णय-सहायक है। वास्तविक उपयोगकर्ताओं के साथ प्रभाव और वास्तविक संदेशों पर त्रुटि दर मापी नहीं गई। निवेश सलाह या नुकसान रोकने की गारंटी नहीं।':'This is a decision aid under development. Effectiveness with real users and error rates on real messages have not been measured. No investment advice or guarantee of preventing loss.'}</p>
 </section>;
}
