// Built bundle + real FastAPI. Optional axe dependency kept outside product.
import {chromium} from 'playwright';
import {spawn} from 'node:child_process';
import {mkdirSync,writeFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const root=new URL('../../',import.meta.url).pathname;
const api=spawn(root+'backend/.venv/bin/uvicorn',['app.main:app','--host','127.0.0.1','--port','8000'],{cwd:root+'backend',stdio:'ignore'});
const browser=await chromium.launch();const folder='/tmp/tipcheck-stage4';mkdirSync(folder,{recursive:true});
const axe=process.env.AXE_PATH || '/tmp/tipcheck-audit/node_modules/axe-core/axe.min.js';
const audits=[];
const specimen='<img src=x onerror="window.__injected=true"> Invest 499 and I will give you 1500. https://example.test/'+ 'a'.repeat(900);
try {
 for(let i=0;i<100;i++){try{if((await fetch('http://127.0.0.1:8000/health')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 for(const width of [320,390,1440]){
  const page=await browser.newPage({viewport:{width,height:1000},reducedMotion:'reduce'});const errors=[],sent=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.method()==='POST')sent.push(r);});
  const check=async name=>{await page.waitForTimeout(350);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,name+' overflow');await page.addScriptTag({path:axe});const result=await page.evaluate(async()=>await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}}));audits.push({width,name,violations:result.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>({html:n.html,summary:n.failureSummary}))}))});await page.screenshot({path:`${folder}/${width}-${name}.png`,fullPage:true});};
  await page.goto('http://127.0.0.1:8000');await page.locator('h2').waitFor();for(let i=0;i<6 && !(await page.locator('.skip-link').evaluate(e=>e===document.activeElement));i++)await page.keyboard.press('Shift+Tab');assert.equal(await page.locator('.skip-link').evaluate(e=>e===document.activeElement),true);await page.keyboard.press('Enter');assert.equal(await page.locator('main').evaluate(e=>e===document.activeElement),true);await check('start');
  await page.getByRole('button',{name:/^A message/}).click();await page.getByRole('heading',{name:'Look at the message'}).waitFor();assert.equal(await page.locator('h1').evaluate(e=>e===document.activeElement),true);await page.locator('#msg').fill(specimen);await check('message');await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByRole('heading',{name:'Review before analysis'}).waitFor();assert.equal(await page.locator('.review-message img').count(),0);assert.equal(sent.length,0);await check('review');
  await page.getByRole('button',{name:'Send details and analyse',exact:true}).click();await page.getByRole('heading',{name:'Your check result'}).waitFor();assert.equal(await page.evaluate(()=>Boolean(window.__injected)),false);assert.equal(await page.locator('.detected-links a').count(),0);await check('hostile-result');await page.getByRole('link',{name:'What to do next',exact:true}).click();await page.getByRole('heading',{name:'Your action plan'}).waitFor();await check('actions');await page.goBack();await page.getByRole('heading',{name:'Your check result'}).waitFor();await page.goForward();await page.getByRole('heading',{name:'Your action plan'}).waitFor();
  // 200% text enlargement catches clipping independently of 320px reflow.
  await page.evaluate(()=>{const elements=[...document.querySelectorAll('body *')];const sizes=elements.map(e=>parseFloat(getComputedStyle(e).fontSize));elements.forEach((e,i)=>e.style.setProperty('font-size',sizes[i]*2+'px','important'));});await check('actions-200pct');await page.reload();await page.getByRole('heading',{name:'Look at the message'}).waitFor();
  for(const route of ['recipient','name','amount','pressure','pin','access']){await page.goto('http://127.0.0.1:8000/#/check/'+route);await page.locator('input[type="radio"]').first().waitFor();await page.locator('input[value="unknown"]').focus();await page.keyboard.press('ArrowLeft');assert.equal(await page.locator('input[type="radio"]:checked').count(),1);await check(route);await page.locator('.language-control select').selectOption('hi');await check(route+'-hi');await page.locator('.language-control select').selectOption('en');}
  for(const route of ['help','about','learn']){await page.goto(`http://127.0.0.1:8000/#/${route}`);await page.locator('h1').waitFor();await check(route);await page.locator('.language-control select').selectOption('hi');await check(route+'-hi');await page.locator('.language-control select').selectOption('en');}
  // Missing old backend endpoint, bad JSON, unsafe source, wrong payload must fail closed.
  await page.goto('http://127.0.0.1:8000');await page.getByRole('button',{name:/^A message/}).click();await page.locator('#msg').fill('ordinary fictional message');await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByRole('heading',{name:'Review before analysis'}).waitFor();
  const real=await (await fetch('http://127.0.0.1:8000/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:'Invest 499 and I will give you 1500.'})})).json();
  for(const response of [{status:404,body:'missing'}, {status:200,body:'not json'}, {status:200,body:'{}'}, {status:200,body:JSON.stringify({...real,risk_score:-1})}, {status:200,body:JSON.stringify({...real,flags:[{...real.flags[0],source:'javascript:alert(1)'}]})}]){await page.route('**/api/analyze',r=>r.fulfill({...response,contentType:'application/json'}));await page.getByRole('button',{name:'Send details and analyse',exact:true}).click();await page.getByRole('alert').waitFor();assert.equal(await page.locator('.result-panel').count(),0);await page.unroute('**/api/analyze');}
  await check('error');await page.locator('.language-control select').selectOption('hi');await check('error-hi');await page.locator('.language-control select').selectOption('en');
  // Navigation interrupts waiting, cannot accept it later; no automatic retry.
  const before=sent.length;await page.route('**/api/analyze',async r=>{await new Promise(resolve=>setTimeout(resolve,400));try{await r.fulfill({status:200,contentType:'application/json',body:JSON.stringify(real)});}catch{}});await page.getByRole('button',{name:'Send details and analyse',exact:true}).click();await page.getByRole('link',{name:'Urgent help',exact:true}).click();await page.getByRole('heading',{name:'Urgent help',exact:true}).waitFor();await page.waitForTimeout(700);assert.equal(sent.length,before+1);assert.equal(await page.locator('.result-panel').count(),0);await page.unroute('**/api/analyze');
  await page.goto('http://127.0.0.1:8000/#/check/result?text=fictional');await page.getByRole('button',{name:/^A message/}).waitFor();assert.equal(await page.locator('.result-panel').count(),0);assert.equal(await page.evaluate(()=>localStorage.length+sessionStorage.length),0);assert.deepEqual(errors,[]);await page.close();console.log(`${width}px: keyboard/focus, axes EN/HI, enlarged text, hostile strings/long URLs, malformed backend/404, cancellation, private-state guards passed`);
 }
 writeFileSync(folder+'/axe.json',JSON.stringify(audits,null,2));
 const failures=audits.filter(a=>a.violations.length);console.log(JSON.stringify(failures,null,2));assert.equal(failures.length,0,'axe violations');
} finally {await browser.close();api.kill();}
